### ISSUE TITLE
0.0.55 crash when updating occupancy true. Back to 0.0.52 everything works great 

### ISSUE THREAD

**Issue by DJay-X** [benzman81/homebridge-http-webhooks#80]
Since update to v0.0.55 homebridge is crashing when occupancy is going to true.
Rollback to v0.0.52 everything is working great again.

Hope you can help. Thx.

```
 {
            "platform": "HttpWebHooks",
            "webhook_port": "51828",
            "http_auth_user": "myuser",
            "http_auth_pass": "ABC1DEfghi&j2KLmn-o",
            "sensors": [
                {
                    "id": "sensor1",
                    "name": "Bett",
                    "type": "occupancy",
                    "autoRelease": false
                }
            ]
        }
```

```
Jan 16 11:17:19 pi-zero homebridge[1124]: [1/16/2020, 11:17:19 AM] [HttpWebHooks] Getting current state for 'sensor1'...
Jan 16 11:17:19 pi-zero homebridge[1124]: [1/16/2020, 11:17:19 AM] [HttpWebHooks] State for 'sensor1' is 'false'
Jan 16 11:17:28 pi-zero homebridge[1124]: [1/16/2020, 11:17:28 AM] [HttpWebHooks] Getting current state for 'sensor1'...
Jan 16 11:17:28 pi-zero homebridge[1124]: [1/16/2020, 11:17:28 AM] [HttpWebHooks] State for 'sensor1' is 'false'
Jan 16 11:17:42 pi-zero homebridge[1124]: [1/16/2020, 11:17:42 AM] TypeError: listener is not a function
Jan 16 11:17:42 pi-zero homebridge[1124]:     at Basic.auth.check (/usr/local/lib/node_modules/homebridge-http-webhooks/node_modules/http-auth/src/server/http.js:30:25)
Jan 16 11:17:42 pi-zero homebridge[1124]:     at Basic.isAuthenticated (/usr/local/lib/node_modules/homebridge-http-webhooks/node_modules/http-auth/src/auth/base.js:100:30)
Jan 16 11:17:42 pi-zero homebridge[1124]:     at Basic.findUser (/usr/local/lib/node_modules/homebridge-http-webhooks/node_modules/http-auth/src/auth/base.js:125:30)
Jan 16 11:17:42 pi-zero homebridge[1124]:     at checker.apply (/usr/local/lib/node_modules/homebridge-http-webhooks/node_modules/http-auth/src/auth/basic.js:88:26)
Jan 16 11:17:42 pi-zero homebridge[1124]:     at Basic.checker (/usr/local/lib/node_modules/homebridge-http-webhooks/index.js:467:9)
Jan 16 11:17:42 pi-zero homebridge[1124]:     at Basic.findUser (/usr/local/lib/node_modules/homebridge-http-webhooks/node_modules/http-auth/src/auth/basic.js:79:26)
Jan 16 11:17:42 pi-zero homebridge[1124]:     at Basic.isAuthenticated (/usr/local/lib/node_modules/homebridge-http-webhooks/node_modules/http-auth/src/auth/base.js:124:22)
Jan 16 11:17:42 pi-zero homebridge[1124]:     at Basic.check (/usr/local/lib/node_modules/homebridge-http-webhooks/node_modules/http-auth/src/auth/base.js:82:14)
Jan 16 11:17:42 pi-zero homebridge[1124]:     at Server.newListener (/usr/local/lib/node_modules/homebridge-http-webhooks/node_modules/http-auth/src/server/http.js:24:22)
Jan 16 11:17:42 pi-zero homebridge[1124]:     at Server.emit (events.js:193:13)
Jan 16 11:17:42 pi-zero homebridge[1124]: [1/16/2020, 11:17:42 AM] Got SIGTERM, shutting down Homebridge...
Jan 16 11:17:45 pi-zero homebridge[1124]: [1/16/2020, 11:17:45 AM] [Config] Homebridge Config UI X v4.7.0 is listening on :: port 8080
Jan 16 11:17:47 pi-zero systemd[1]: homebridge.service: Main process exited, code=exited, status=143/n/a
Jan 16 11:17:47 pi-zero systemd[1]: homebridge.service: Failed with result 'exit-code'.
```

**Comment by DJay-X** [comment]
Haven't noticed before https://github.com/benzman81/homebridge-http-webhooks/issues/79 because of pointing to IFTTT but could be related to the issue as well.

**Comment by benzman81** [comment]
Version 0.0.56 should fix it. Please verify if it works now.

**Comment by DJay-X** [comment]
Works like charm again. My friday morning coffee is save again. ;) Thanks a lot. 👍
